<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shisha.Domain\Shisha.Domain.csproj" />
    <ProjectReference Include="..\Shisha.Application\Shisha.Application.csproj" />
    <ProjectReference Include="..\Shisha.Infrastructure\Shisha.Infrastructure.csproj" />
  </ItemGroup>

</Project>
